server:
  port: 9090
spring:
  application:
    name: eurka-server
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    eureka-server-u-r-l-context: http://${eureka.instance.hostname}:${server.port}/eureka/